export const GET_MOVIES_REQUEST = "GET_MOVIES_REQUEST";
export const GET_MOVIES_FAIL = "GET_MOVIES_FAIL";
export const GET_MOVIES_SUCCESS = "GET_MOVIES_SUCCESS";
export const GET_TV_SUCCESS = "GET_TV_SUCCESS";
export const GET_GENRES_MOVIE = "GET_GENRES_MOVIE";
export const GET_ITEM_DETAILS = "GET_ITEM_DETAILS";
export const GET_ITEM_DETAILS_REQUEST = "GET_ITEM_DETAILS_REQUEST";
